### ISSUE TITLE
Cannot Access Current User

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-feed-flutter#186]
Im still not able to access the current user after setting the user since updating. Old ticket #177 

This is my riverpod provider:
```
final streamUser = FutureProvider.autoDispose((ref) async {
  final streamClient = ref.read(client);
  final currentUser = ref.watch(userAccount);
  if (streamClient != null && currentUser.asData!.value.uid != null) {
    print('Feed User set.');
    var u =
        '${currentUser.asData!.value.uid}_${currentUser.asData!.value.currentAccount}';
    final user = await streamClient.setUser(
        feed.User(
          id: u,
        ),
        feed.Token(currentUser.asData!.value.currentToken!));
    await streamClient.currentUser!.profile();
    return user;
  }
  return Future.value();
});
```
and the function where I first get a user:
```
widget.streamClient.currentUser!.get().then((value) {
      var data = value.data;
      
      setState(() {
        image = data!['photo'] as String;
        name = data['name'] as String;
      });
      fetchStories();
    });
```
@xsahil03x

**Comment by HayesGordon** [comment]
Hi @rlee1990

Could you also share your `client` and `userAccount` providers.

At what point are you calling the `streamUser` provider, it could be that where you're accessing `widget.client.currentUser` in your Stateful widget the providers have not been triggered, or the `setUser` future has not completed.

Please note that you do not need to call `get` again after calling `setUser`. After awaiting `setUser` the current user will be available synchronously on the Feed client through: `streamClient.currentUser`.

So instead of calling setState you could directly pass in the properties to your widget:
```dart
final user = streamClient.currentUser;
return MyWidget(data: user.data);
```

But this will require that you await for the `streamUser` provider to have completed.

From a Riverpod perspective I would recommend that all you actually need is the `client` provider. Then you can always just do `ref.read(clientProvider).currentUser` to get the user. But before doing this you need to have done the following somewhere in your app: `await ref.read(clientProvider).setUser(user, token)`;

**Comment by rlee1990** [comment]
@HayesGordon Here is my other providers.
```
final userAccount = StreamProvider<UserAccount>((ref) {
  final auth = ref.watch(authStateChangesProvider);
  return FirestoreService().streamUserAccount(auth.asData?.value?.uid);
});
final client = Provider.autoDispose<feed.StreamFeedClient?>((ref) {
  final currentUser = ref.watch(userAccount);
  if (currentUser.asData!.value.uid!.isNotEmpty) {
    final token = currentUser.asData!.value.currentToken;
    return feed.StreamFeedClient(dotenv.env['STREAM_FEED_KEY'] as String,
        token: feed.Token(token!), appId: '92418');
  }
  return null;
});
```
I call streamUser and wait for that to return before I load the home page or any page.

**Comment by rlee1990** [comment]
@HayesGordon Don't we have to set a current user before we can call `streamClient.currentUser;`?

**Comment by rlee1990** [comment]
Think I have it working now.

**Comment by HayesGordon** [comment]
I'm glad @rlee1990, and yes you're right the docs need improving! That is something that we are working on.

**Comment by rlee1990** [comment]
@HayesGordon thanks for the help. It pointed me in the correct direction.
