### ISSUE TITLE
Stream Token Issue

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-feed-flutter#54]
I am receiving this exception:
`'package:stream_feed/src/client/stream_feed_client_impl.dart': Failed assertion: line 61 pos 9: 'userId != null': Invalid `userToken`, It should contain `user_id``
I receive it when passing the token from my backend to the front end. The issue appears because we have to pass a token object and not a string. Are we supposed to still create the token via our backend server or just make it in the app?

**Comment by Nash0x7E2** [comment]
Hi! Thank you for filing this issue! 

You are receiving this error because the user token generated from your backend does not match the user's ID on the frontend. 

All tokens created on the backend should be generated using your application's secret and a `user_id`. As an example, you can enter your application's secret and a test user ID on our online generator to create a token then pass that to your application. 

Online Generator: https://getstream.io/chat/docs/react/token_generator/

For more information on Stream's authentication using tokens, check out the following:
- https://getstream.io/activity-feeds/docs/node/auth_and_permissions/?language=javascript#client-side-auth
- https://getstream.io/activity-feeds/docs/node/auth_and_permissions/?language=javascript#user-tokens

Hope this helps!

**Comment by rlee1990** [comment]
Thanks I will give it a try and let you know what happens.

**Comment by rlee1990** [comment]
I found the issue with that was happening I was using `streamClient.user(newValue.uid).getOrCreate({name: newValue.name, gender: newValue.gender, photo: newValue.profileFile.url});` to create the token which was not creating the correct token I guess now I am using `streamClient.createUserToken(streamUser.id);` thanks
